# ------------------------------
#      MODEL + TRAINING
# ------------------------------

model: "ImprovedK2C2CNN"
seed: 42

# Use full dataset
#subset_size: 90086   # or remove this line entirely

epochs: 20

# Base LR (only used as initial lr for AdamW before OneCycle takes over)
lr: 0.0001          
weight_decay: 0.0001

batch_size: 32
num_workers: 16

use_normalization: true
mel_mean: -45.0
mel_std: 12.0


# ------------------------------
#      Optimizer Settings
# ------------------------------

optimizer: "adamw"

# ------------------------------
#      LR Scheduler (OneCycleLR)
# ------------------------------

scheduler: "onecycle"

# Peak LR during OneCycle
max_lr: 0.0005

# Final LR after annealing
final_lr: 0.00001

# Start with a warmup of 30% of the cycle
pct_start: 0.3

# ------------------------------
#      Data Augmentation
# ------------------------------

use_specaugment: false

# You may keep these defaults for future experiments
specaugment:
  freq_masks: 2
  time_masks: 2
  freq_max_width: 20
  time_max_width: 50
