# configs/crnn_v2.yaml

model: "CRNNv2Uni"   # or "CRNNv2Bi"
seed: 42

epochs: 20

batch_size: 32
num_workers: 16

lr: 0.0001
weight_decay: 0.0001

optimizer: "adamw"

scheduler: "onecycle"
max_lr: 0.0005
final_lr: 0.00001
pct_start: 0.3

use_specaugment: false

specaugment:
  freq_masks: 2
  time_masks: 2
  freq_max_width: 20
  time_max_width: 50
