model: "ResidualK2C2CNN"
seed: 42
epochs: 20

lr: 0.0001
weight_decay: 0.0003

batch_size: 32
num_workers: 16

optimizer: "adamw"

scheduler: "onecycle"
max_lr: 0.0005
final_lr: 0.00001
pct_start: 0.3

use_specaugment: true

specaugment:
  freq_masks: 3
  time_masks: 3
  freq_max_width: 24
  time_max_width: 60